"use client"
import './globals.css';
import Navbar from './components/Navbar/index';
import Footer from './components/Footer/Footer';
import { RouterProvider } from 'react-router-dom';
import { ROUTES } from './core/constants/routers';


 const metadata = {
  title: 'Courses',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <RouterProvider router={ROUTES} />
      </body>
    </html>
  )
}
